/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NumerologyRouteImport } from './routes/numerology'
import { Route as RestSessionsRouteImport } from './routes/rest-sessions'
import { Route as ShopRouteImport } from './routes/shop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerologyRoute = NumerologyRouteImport.update({
  id: '/numerology',
  path: '/numerology',
  getParentRoute: () => rootRouteImport,
} as any)
const RestSessionsRoute = RestSessionsRouteImport.update({
  id: '/rest-sessions',
  path: '/rest-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/numerology': typeof NumerologyRoute
  '/rest-sessions': typeof RestSessionsRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/numerology': typeof NumerologyRoute
  '/rest-sessions': typeof RestSessionsRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/numerology': typeof NumerologyRoute
  '/rest-sessions': typeof RestSessionsRoute
  '/shop': typeof ShopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/numerology' | '/rest-sessions' | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/numerology' | '/rest-sessions' | '/shop'
  id: '__root__' | '/' | '/numerology' | '/rest-sessions' | '/shop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NumerologyRoute: typeof NumerologyRoute
  RestSessionsRoute: typeof RestSessionsRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numerology': {
      id: '/numerology'
      path: '/numerology'
      fullPath: '/numerology'
      preLoaderRoute: typeof NumerologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rest-sessions': {
      id: '/rest-sessions'
      path: '/rest-sessions'
      fullPath: '/rest-sessions'
      preLoaderRoute: typeof RestSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NumerologyRoute: NumerologyRoute,
  RestSessionsRoute: RestSessionsRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
